### ISSUE TITLE
1000 common English words

### ISSUE THREAD

**Issue by vu3rdd** [k0tet/morsetrainer#26]
Hi - Thanks for the great app and thanks for making it free software.

Would you mind including a text file that has the 1000 common english words - like the one available here? 

https://gist.githubusercontent.com/deekayen/4148741/raw/01c6252ccc5b5fb307c1bb899c95989a8a284616/1-1000.txt

Cheers
Ram

**Comment by cniesen** [comment]
You can create your own custom files with characters, words or phrases that you want to learn. Just create a text file with each character, word or phrase on a separate line. If the Morse text and spoken text is different then separate them with a vertical pipe "|". E.g.:  `tu|thank you`

Place the file into the "Claus' Morse Trainer" directory on your phone and next time the app is started the word list will be available.

**Comment by vu3rdd** [comment]
Thanks. I did exactly that just a few minutes after posting that issue, but forgot to write about it here.

Thanks for the tip on the spoken text and the vertical pipe. That is very very useful. Thanks. I guess I will go ahead and close this issue.
